### ISSUE TITLE
Auto Install Package

### ISSUE THREAD

**Issue by VikashKotharyWork** [amclin/aem-packager#186]
**Is your feature request related to a problem? Please describe.**
It is common to have a Maven Profile to install the package into an AEM instance. It would be nice to have that here.

**Describe the solution you'd like**
A flag to auto-install the package into an AEM instance.

**Describe alternatives you've considered**
I'm currently using the AEM curl command to install the package after the package has been built.

**Additional context**

**Comment by amclin** [comment]
That highly depends on how you are going from Maven to AEM, and makes sense when you're running the build on the same machine as the running AEM instance. Generally that's not a good practice (though I know a lot of teams do this). For example, for security purposes you don't need and shouldn't have NodeJS or any of your other dev dependencies installed on your running AEM app servers. 

Handling the responsibility of when to install which package to which AEM App server is best delegated to an automation system designed to handle those kinds of operations:
* Jenkins
* Bamboo
* Travis
* Azure DevOps
etc...

That way you have auditable logs, the ability to reconfigure or dynamically map which packages go to which servers in which order, status of deployments, blue/green/rolling deployments, etc.

**Comment by amclin** [comment]
Since installation management and pipelines is outside the scope of this project, I'm going to close this request.

I'm sure a maven wrapper can be written to go around the packages produced by this library, but it would be highly-specific to the environment, and not easily abstracted.

@VikashKotharyWork thank you for the suggestion!
