### ISSUE TITLE
Option to not have datetime-stamp in filename of build

### ISSUE THREAD

**Issue by MikaelX** [amclin/aem-packager#296]
I would like an option to not include the datetime-stamp in the output filename

**Comment by amclin** [comment]
@MikaelX can you explain your use case? AEM really really doesn't like uploading packages with the non-unique filenames, which is why the timestamp is used to guarantee uniqueness:
https://github.com/amclin/aem-packager#package-filename

**Comment by amclin** [comment]
Closing for lack of explanation
