### ISSUE TITLE
jcrPath option not used

### ISSUE THREAD

**Issue by sovanyio** [amclin/aem-packager#40]
**Describe the bug**
The `jcrPath` option is not used currently.

**To Reproduce**
1. Define `jcrPath`
2. Build
3. Observe default directory used

**Expected behavior**
Expect the built package to use the `jcrPath` defined in the options.

**Environment (please complete the following information):**
Not relevant

**Additional context**
I fixed this in a fork, will PR it :). Looks like there is a different method used when grabbing the options passed `jcrRoot` vs `srcDir` and `buildDir`; grabbing jcrPath using the `resolvePath` method like the other options corrects this.

**Comment by amclin** [comment]
@sovanyio can you check if #43 fixes your issue?

**Comment by sovanyio** [comment]
Yep, thanks for the fix and the explanation!
